import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Navbar from './components/common/navBar'

const inter = Inter({ subsets: ['latin'] })
const cardStyle: React.CSSProperties = {
  width: '80vw',
  height: "70vh",
  border: '1px solid #ccc',
  boxShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
  padding: '20px',
  margin: '20px auto',
  backgroundColor: '#fff',
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  flexDirection: "column"
};
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{backgroundColor:"violet"}} className={inter.className} >
       
        <div >
        <Navbar/>{children}
        </div>
        
        
  
        </body>
        
    </html>
  )
}
